name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  firebase_core: any
  image_picker: ^1.0.4
  fluttertoast: ^8.2.2
  firebase_database: ^10.2.6
  confirm_dialog: ^1.0.2
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  page_transition: ^2.1.0
  flutter_local_notifications: ^9.8.0+1
  firebase_messaging: ^14.7.1
  intl: ^0.18.1
  rxdart: ^0.27.7
  pay: ^1.1.2
  url_launcher: ^6.2.1
  carousel_slider: ^4.2.1
  pie_chart: ^5.4.0
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/page-1/images/logomau.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/ant-design-eye-invisible-filled.png
    - assets/page-1/images/ant-design-eye-invisible-filled-Mng.png
    - assets/page-1/images/ant-design-eye-invisible-filled-4iC.png
    - assets/page-1/images/ant-design-eye-invisible-filled-jng.png
    - assets/page-1/images/ant-design-eye-invisible-filled-fsn.png
    - assets/page-1/images/ant-design-eye-invisible-filled-EzU.png
    - assets/page-1/images/imggioithieu4.png
    - assets/page-1/images/logomau.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/frame-52.png
    - assets/page-1/images/frame-53.png
    - assets/page-1/images/btxoa-CLg.png
    - assets/page-1/images/btxoa.png
    - assets/page-1/images/btedit.png
    - assets/page-1/images/imggioithieu3.png
    - assets/page-1/images/hinhnen1-bg.png
    - assets/page-1/images/btxoa-Pm2.png
    - assets/page-1/images/vector-PAg.png
    - assets/page-1/images/btedit-juz.png
    - assets/page-1/images/btsapxep.png
    - assets/page-1/images/vector-rdn.png
    - assets/page-1/images/search.png
    - assets/page-1/images/imggioithieu2-1.png
    - assets/page-1/images/btedit-jqr.png
    - assets/page-1/images/trash-2.png
    - assets/page-1/images/btedit-h3E.png
    - assets/page-1/images/frame-49.png
    - assets/page-1/images/edit.png
    - assets/page-1/images/btxoa-HRA.png
    - assets/page-1/images/search-df6.png
    - assets/page-1/images/btedit-pJC.png
    - assets/page-1/images/btedit-jNg.png
    - assets/page-1/images/btedit-gLg.png
    - assets/page-1/images/btxoa-Be8.png
    - assets/page-1/images/vector-Lqn.png
    - assets/page-1/images/hinhnen2-bg.png
    - assets/page-1/images/btedit-uSG.png
    - assets/page-1/images/auto-group-s6a4.png
    - assets/page-1/images/frame-48.png
    - assets/page-1/images/search-3mz.png
    - assets/page-1/images/vector-kZE.png
    - assets/page-1/images/auto-group-cur8.png
    - assets/page-1/images/hinhnen2-bg-q3W.png
    - assets/page-1/images/hinhnen2-bg-tQG.png
    - assets/page-1/images/btedit-3HA.png
    - assets/page-1/images/btedit-w1i.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/btedit-Qvt.png
    - assets/page-1/images/btedit-EPS.png
    - assets/page-1/images/btsapxep-nwa.png
    - assets/page-1/images/image-16-tHn.png
    - assets/page-1/images/btedit-gik.png
    - assets/page-1/images/clarity-notification-solid-badged.png
    - assets/page-1/images/vector-rq6.png
    - assets/page-1/images/anhsp.png
    - assets/page-1/images/btsapxep-xVv.png
    - assets/page-1/images/btedit-1NG.png
    - assets/page-1/images/btxoa-Uh6.png
    - assets/page-1/images/btxoa-vFa.png
    - assets/page-1/images/btxoa-H68.png
    - assets/page-1/images/btxoa-zyW.png
    - assets/page-1/images/image-16-ZUt.png
    - assets/page-1/images/coffee-bag.png
    - assets/page-1/images/btxoa-3zG.png
    - assets/page-1/images/btxoa-A9W.png
    - assets/page-1/images/btxoa-FaG.png
    - assets/page-1/images/anhsp-3Vz.png
    - assets/page-1/images/anhsp-pCx.png
    - assets/page-1/images/vector-8G8.png
    - assets/page-1/images/image-16-2jS.png
    - assets/page-1/images/anhsp-Esz.png
    - assets/page-1/images/coffee-cup.png
    - assets/page-1/images/imggioithieu1.png
    - assets/page-1/images/btxoa-264.png
    - assets/page-1/images/frame.png
    - assets/page-1/images/image-16-3qi.png
    - assets/page-1/images/image-16-dDS.png
    - assets/page-1/images/staff.png
    - assets/page-1/images/image-16-r6k.png
    - assets/page-1/images/anhsp-gbS.png
    - assets/page-1/images/anhsp-y6Y.png
    - assets/page-1/images/hinhnen1-1-bg.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/anhsp-Sfi.png
    - assets/page-1/images/anhsp-u28.png
    - assets/page-1/images/anhsp-t88.png
    - assets/page-1/images/btedit-Dax.png
    - assets/page-1/images/anhsp-bip.png
    - assets/page-1/images/pie-chart.png
    - assets/page-1/images/anhsp-k4G.png
    - assets/page-1/images/anhsp-3vG.png
    - assets/page-1/images/frame-DgC.png
    - assets/page-1/images/vector-25v.png
    - assets/page-1/images/coffee-cup-7Ri.png
    - assets/page-1/images/clarity-notification-solid-badged-hF6.png
    - assets/page-1/images/vector-XmS.png
    - assets/page-1/images/coffee-bag-gKi.png
    - assets/page-1/images/vector-rj2.png
    - assets/page-1/images/frame-48-cQp.png
    - assets/page-1/images/vector-xXA.png
    - assets/page-1/images/frame-52-9we.png
    - assets/page-1/images/frame-49-Z3N.png
    - assets/page-1/images/vector-3g4.png
    - assets/page-1/images/frame-53-6AC.png
    - assets/page-1/images/btsapxep-Yrt.png
    - assets/page-1/images/vector-RvQ.png
    - assets/page-1/images/btxoa-1Da.png
    - assets/page-1/images/anhsp-M2Y.png
    - assets/page-1/images/anhsp-ERE.png
    - assets/page-1/images/btedit-GZE.png
    - assets/page-1/images/btxoa-GmN.png
    - assets/page-1/images/edit-Uoa.png
    - assets/page-1/images/btxoa-4oz.png
    - assets/page-1/images/btxoa-Whv.png
    - assets/page-1/images/btedit-jxt.png
    - assets/page-1/images/anhsp-fMz.png
    - assets/page-1/images/btedit-RfE.png
    - assets/page-1/images/btxoa-7EY.png
    - assets/page-1/images/anhsp-Sec.png
    - assets/page-1/images/search-9XW.png
    - assets/page-1/images/btxoa-Eo2.png
    - assets/page-1/images/btedit-A5e.png
    - assets/page-1/images/btedit-d12.png
    - assets/page-1/images/search-aEt.png
    - assets/page-1/images/btedit-JAk.png
    - assets/page-1/images/btedit-CQx.png
    - assets/page-1/images/btxoa-5pC.png
    - assets/page-1/images/btedit-ga4.png
    - assets/page-1/images/auto-group-z8nu.png
    - assets/page-1/images/vector-4rc.png
    - assets/page-1/images/btxoa-6At.png
    - assets/page-1/images/btedit-pNC.png
    - assets/page-1/images/trash-2-GsS.png
    - assets/page-1/images/vector-Rvx.png
    - assets/page-1/images/btsapxep-oMJ.png
    - assets/page-1/images/image-11-MCL.png
    - assets/page-1/images/btxoa-Lfa.png
    - assets/page-1/images/anhsp-cHW.png
    - assets/page-1/images/vector-kfr.png
    - assets/page-1/images/anhsp-6cx.png
    - assets/page-1/images/anhsp-kRn.png
    - assets/page-1/images/memory-alpha-i.png
    - assets/page-1/images/anhsp-e8p.png
    - assets/page-1/images/ph-phone-fill.png
    - assets/page-1/images/anhsp-ZhJ.png
    - assets/page-1/images/anhsp-UUg.png
    - assets/page-1/images/ellipse-3-bg.png
    - assets/page-1/images/octicon-person-16.png
    - assets/page-1/images/memory-alpha-i-QXr.png
    - assets/page-1/images/anhmagiamgia.png
    - assets/page-1/images/ph-phone-fill-s52.png
    - assets/page-1/images/anhsp-H84.png
    - assets/page-1/images/anhsp-a8g.png
    - assets/page-1/images/vector-og4.png
    - assets/page-1/images/ellipse-3-bg-nak.png
    - assets/page-1/images/ri-logout-box-r-line.png
    - assets/page-1/images/ellipse-3-bg-fL4.png
    - assets/page-1/images/octicon-person-16-4PS.png
    - assets/page-1/images/ph-phone-fill-RcL.png
    - assets/page-1/images/group.png
    - assets/page-1/images/ri-logout-box-r-line-9fW.png
    - assets/page-1/images/octicon-person-16-FQc.png
    - assets/page-1/images/vector-Q6C.png
    - assets/page-1/images/memory-alpha-i-AKz.png
    - assets/page-1/images/ri-logout-box-r-line-EXi.png
    - assets/page-1/images/group-56.png
    - assets/page-1/images/group-56-pXA.png
    - assets/page-1/images/vector-Wr4.png
    - assets/page-1/images/vector-VXv.png
    - assets/page-1/images/map.png
    - assets/page-1/images/email-marketing.png
    - assets/page-1/images/facebook.png
    - assets/page-1/images/instagram.png
    - assets/page-1/images/smartphone.png
    - assets/page-1/images/vector-JZE.png
    - assets/page-1/images/frame-50.png
    - assets/page-1/images/frame-50-iDW.png
    - assets/page-1/images/vector-SjS.png
    - assets/page-1/images/vector-QX2.png
    - assets/page-1/images/vector-FmS.png
    - assets/page-1/images/vectomenu.png
    - assets/page-1/images/vector-yJQ.png
    - assets/page-1/images/image-16-y1r.png
    - assets/page-1/images/vectorthongbao.png
    - assets/page-1/images/vector-TK6.png
    - assets/page-1/images/iconxemthem.png
    - assets/page-1/images/search-V7e.png
    - assets/page-1/images/unsplash-qbvpsw2pzve-bg.png
    - assets/page-1/images/vector-DHS.png
    - assets/page-1/images/hinhsp-bg.png
    - assets/page-1/images/image-9-bg.png
    - assets/page-1/images/ion-bag-add-outline.png
    - assets/page-1/images/vector-6jz.png
    - assets/page-1/images/hinhsp-bg-kd6.png
    - assets/page-1/images/image-7-bg.png
    - assets/page-1/images/unsplash-sf7v0cnhpmw-bg.png
    - assets/page-1/images/ion-bag-add-outline-Abz.png
    - assets/page-1/images/anhsp-SPA.png
    - assets/page-1/images/ant-design-home-filled.png
    - assets/page-1/images/anhsp-F4C.png
    - assets/page-1/images/image-10-bg.png
    - assets/page-1/images/anhsp-YuW.png
    - assets/page-1/images/anhsp-HCk.png
    - assets/page-1/images/group-jqi.png
    - assets/page-1/images/auto-group-wi64.png
    - assets/page-1/images/anhsp-iSt.png
    - assets/page-1/images/iconamoon-shopping-bag-light.png
    - assets/page-1/images/iconsapxep.png
    - assets/page-1/images/ion-bag-add-outline-2mv.png
    - assets/page-1/images/mdi-arrange-send-backward.png
    - assets/page-1/images/group-fbe.png
    - assets/page-1/images/vector-GLx.png
    - assets/page-1/images/btyeuthich.png
    - assets/page-1/images/carbon-favorite.png
    - assets/page-1/images/vector-Eyn.png
    - assets/page-1/images/image-8-bg.png
    - assets/page-1/images/vector-Usr.png
    - assets/page-1/images/ph-coffee.png
    - assets/page-1/images/ion-bag-add-outline-QHe.png
    - assets/page-1/images/search-iLG.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/vector-TRa.png
    - assets/page-1/images/anhsp-RZJ.png
    - assets/page-1/images/auto-group-rjyg.png
    - assets/page-1/images/btyeuthich-ret.png
    - assets/page-1/images/btyeuthich-1Xn.png
    - assets/page-1/images/vector-BBN.png
    - assets/page-1/images/btyeuthich-wbn.png
    - assets/page-1/images/group-Qfa.png
    - assets/page-1/images/vector-CZv.png
    - assets/page-1/images/group-imN.png
    - assets/page-1/images/anhsp-GBA.png
    - assets/page-1/images/material-symbols-delete.png
    - assets/page-1/images/vector-QPr.png
    - assets/page-1/images/auto-group-wt5z.png
    - assets/page-1/images/material-symbols-delete-qSp.png
    - assets/page-1/images/auto-group-acfa.png
    - assets/page-1/images/auto-group-ohha.png
    - assets/page-1/images/search-pBi.png
    - assets/page-1/images/anhsp-7P6.png
    - assets/page-1/images/auto-group-inal.png
    - assets/page-1/images/mdi-arrange-send-backward-5ax.png
    - assets/page-1/images/anhsp-Dcc.png
    - assets/page-1/images/vector-HQ4.png
    - assets/page-1/images/vector-bDi.png
    - assets/page-1/images/auto-group-sqx2.png
    - assets/page-1/images/auto-group-1ark.png
    - assets/page-1/images/anhsp-gTz.png
    - assets/page-1/images/vector-vNk.png
    - assets/page-1/images/anhsp-GTS.png
    - assets/page-1/images/auto-group-divl.png
    - assets/page-1/images/material-symbols-delete-kiL.png
    - assets/page-1/images/vector-RCc.png
    - assets/page-1/images/auto-group-ps5r.png
    - assets/page-1/images/auto-group-fcuv.png
    - assets/page-1/images/anhsp-Gh6.png
    - assets/page-1/images/material-symbols-delete-fMA.png
    - assets/page-1/images/auto-group-r976.png
    - assets/page-1/images/vector-VrY.png
    - assets/page-1/images/auto-group-m31a.png
    - assets/page-1/images/anhsp-XEx.png
    - assets/page-1/images/auto-group-ptf2.png
    - assets/page-1/images/auto-group-j8wk.png
    - assets/page-1/images/auto-group-c73v.png
    - assets/page-1/images/vector-KvY.png
    - assets/page-1/images/auto-group-gngg.png
    - assets/page-1/images/material-symbols-delete-5J8.png
    - assets/page-1/images/material-symbols-delete-gji.png
    - assets/page-1/images/auto-group-w8qx.png
    - assets/page-1/images/vector-2ji.png
    - assets/page-1/images/auto-group-gbsg.png
    - assets/page-1/images/auto-group-2zp6.png
    - assets/page-1/images/material-symbols-delete-FZi.png
    - assets/page-1/images/auto-group-9gqe.png
    - assets/page-1/images/vector-RK6.png
    - assets/page-1/images/material-symbols-delete-Xmi.png
    - assets/page-1/images/anhsp-BJx.png
    - assets/page-1/images/anhsp-DFe.png
    - assets/page-1/images/euros.png
    - assets/page-1/images/vector-tat.png
    - assets/page-1/images/vector-Y2k.png
    - assets/page-1/images/anhsp-jJp.png
    - assets/page-1/images/anhsp-h8L.png
    - assets/page-1/images/vector-fPE.png
    - assets/page-1/images/image-19.png
    - assets/page-1/images/image-18.png
    - assets/page-1/images/anhsp-LQ8.png
    - assets/page-1/images/vector-2pp.png
    - assets/page-1/images/image-20.png
    - assets/page-1/images/KhongGian.png
    - assets/page-1/images/AddFavorite.png
    - assets/page-1/images/AddCart.png
    - lib/page-1/lienhe.dart
    - assets/
    - assets/page-1/
    - assets/page-1/images/
    - assets/page-1/images/octicon_person-16.png
    - fonts:
         - family: Quicksand
           fonts:
             - asset: assets/fonts/Quicksand-VariableFont_wght.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
